export { default as api } from "./axiosInstance";
export * from "./avc09";
export { default as auth } from "./auth";
export * from "./filePersonnel";
export * from "./hospital";
export * from "./grades";
export * from "./policePersonnel";
export * from "./prenatalCareService";
export * from "./natalDataService";
export * from "./sickLeave";
export * from "./socket";
export * from "./units";
